/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as HeaderRouteRouteImport } from './routes/_header/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LogInIndexRouteImport } from './routes/log-in/index'
import { Route as AuthenticatedAccountRouteRouteImport } from './routes/_authenticated/account/route'
import { Route as HeaderTermsIndexRouteImport } from './routes/_header/terms/index'
import { Route as HeaderPrivacyIndexRouteImport } from './routes/_header/privacy/index'
import { Route as HeaderPricingIndexRouteImport } from './routes/_header/pricing/index'
import { Route as HeaderExploreIndexRouteImport } from './routes/_header/explore/index'
import { Route as HeaderBlogIndexRouteImport } from './routes/_header/blog/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedAccountIndexRouteImport } from './routes/_authenticated/account/index'
import { Route as HeaderBlogSlugRouteImport } from './routes/_header/blog/$slug'
import { Route as AuthenticatedAccountBillingRouteImport } from './routes/_authenticated/account/billing'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const HeaderRouteRoute = HeaderRouteRouteImport.update({
  id: '/_header',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogInIndexRoute = LogInIndexRouteImport.update({
  id: '/log-in/',
  path: '/log-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountRouteRoute =
  AuthenticatedAccountRouteRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const HeaderTermsIndexRoute = HeaderTermsIndexRouteImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => HeaderRouteRoute,
} as any)
const HeaderPrivacyIndexRoute = HeaderPrivacyIndexRouteImport.update({
  id: '/privacy/',
  path: '/privacy/',
  getParentRoute: () => HeaderRouteRoute,
} as any)
const HeaderPricingIndexRoute = HeaderPricingIndexRouteImport.update({
  id: '/pricing/',
  path: '/pricing/',
  getParentRoute: () => HeaderRouteRoute,
} as any)
const HeaderExploreIndexRoute = HeaderExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => HeaderRouteRoute,
} as any)
const HeaderBlogIndexRoute = HeaderBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => HeaderRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAccountRouteRoute,
  } as any)
const HeaderBlogSlugRoute = HeaderBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => HeaderRouteRoute,
} as any)
const AuthenticatedAccountBillingRoute =
  AuthenticatedAccountBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedAccountRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account': typeof AuthenticatedAccountRouteRouteWithChildren
  '/log-in/': typeof LogInIndexRoute
  '/account/billing': typeof AuthenticatedAccountBillingRoute
  '/blog/$slug': typeof HeaderBlogSlugRoute
  '/account/': typeof AuthenticatedAccountIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/blog/': typeof HeaderBlogIndexRoute
  '/explore/': typeof HeaderExploreIndexRoute
  '/pricing/': typeof HeaderPricingIndexRoute
  '/privacy/': typeof HeaderPrivacyIndexRoute
  '/terms/': typeof HeaderTermsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/log-in': typeof LogInIndexRoute
  '/account/billing': typeof AuthenticatedAccountBillingRoute
  '/blog/$slug': typeof HeaderBlogSlugRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/blog': typeof HeaderBlogIndexRoute
  '/explore': typeof HeaderExploreIndexRoute
  '/pricing': typeof HeaderPricingIndexRoute
  '/privacy': typeof HeaderPrivacyIndexRoute
  '/terms': typeof HeaderTermsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_header': typeof HeaderRouteRouteWithChildren
  '/demo': typeof DemoRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/account': typeof AuthenticatedAccountRouteRouteWithChildren
  '/log-in/': typeof LogInIndexRoute
  '/_authenticated/account/billing': typeof AuthenticatedAccountBillingRoute
  '/_header/blog/$slug': typeof HeaderBlogSlugRoute
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_header/blog/': typeof HeaderBlogIndexRoute
  '/_header/explore/': typeof HeaderExploreIndexRoute
  '/_header/pricing/': typeof HeaderPricingIndexRoute
  '/_header/privacy/': typeof HeaderPrivacyIndexRoute
  '/_header/terms/': typeof HeaderTermsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/llms.txt'
    | '/sitemap.xml'
    | '/account'
    | '/log-in/'
    | '/account/billing'
    | '/blog/$slug'
    | '/account/'
    | '/dashboard/'
    | '/blog/'
    | '/explore/'
    | '/pricing/'
    | '/privacy/'
    | '/terms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/llms.txt'
    | '/sitemap.xml'
    | '/log-in'
    | '/account/billing'
    | '/blog/$slug'
    | '/account'
    | '/dashboard'
    | '/blog'
    | '/explore'
    | '/pricing'
    | '/privacy'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_header'
    | '/demo'
    | '/llms.txt'
    | '/sitemap.xml'
    | '/_authenticated/account'
    | '/log-in/'
    | '/_authenticated/account/billing'
    | '/_header/blog/$slug'
    | '/_authenticated/account/'
    | '/_authenticated/dashboard/'
    | '/_header/blog/'
    | '/_header/explore/'
    | '/_header/pricing/'
    | '/_header/privacy/'
    | '/_header/terms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  HeaderRouteRoute: typeof HeaderRouteRouteWithChildren
  DemoRoute: typeof DemoRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  LogInIndexRoute: typeof LogInIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_header': {
      id: '/_header'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HeaderRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log-in/': {
      id: '/log-in/'
      path: '/log-in'
      fullPath: '/log-in/'
      preLoaderRoute: typeof LogInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_header/terms/': {
      id: '/_header/terms/'
      path: '/terms'
      fullPath: '/terms/'
      preLoaderRoute: typeof HeaderTermsIndexRouteImport
      parentRoute: typeof HeaderRouteRoute
    }
    '/_header/privacy/': {
      id: '/_header/privacy/'
      path: '/privacy'
      fullPath: '/privacy/'
      preLoaderRoute: typeof HeaderPrivacyIndexRouteImport
      parentRoute: typeof HeaderRouteRoute
    }
    '/_header/pricing/': {
      id: '/_header/pricing/'
      path: '/pricing'
      fullPath: '/pricing/'
      preLoaderRoute: typeof HeaderPricingIndexRouteImport
      parentRoute: typeof HeaderRouteRoute
    }
    '/_header/explore/': {
      id: '/_header/explore/'
      path: '/explore'
      fullPath: '/explore/'
      preLoaderRoute: typeof HeaderExploreIndexRouteImport
      parentRoute: typeof HeaderRouteRoute
    }
    '/_header/blog/': {
      id: '/_header/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof HeaderBlogIndexRouteImport
      parentRoute: typeof HeaderRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport
      parentRoute: typeof AuthenticatedAccountRouteRoute
    }
    '/_header/blog/$slug': {
      id: '/_header/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof HeaderBlogSlugRouteImport
      parentRoute: typeof HeaderRouteRoute
    }
    '/_authenticated/account/billing': {
      id: '/_authenticated/account/billing'
      path: '/billing'
      fullPath: '/account/billing'
      preLoaderRoute: typeof AuthenticatedAccountBillingRouteImport
      parentRoute: typeof AuthenticatedAccountRouteRoute
    }
  }
}

interface AuthenticatedAccountRouteRouteChildren {
  AuthenticatedAccountBillingRoute: typeof AuthenticatedAccountBillingRoute
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
}

const AuthenticatedAccountRouteRouteChildren: AuthenticatedAccountRouteRouteChildren =
  {
    AuthenticatedAccountBillingRoute: AuthenticatedAccountBillingRoute,
    AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
  }

const AuthenticatedAccountRouteRouteWithChildren =
  AuthenticatedAccountRouteRoute._addFileChildren(
    AuthenticatedAccountRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRouteRoute: typeof AuthenticatedAccountRouteRouteWithChildren
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRouteRoute: AuthenticatedAccountRouteRouteWithChildren,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface HeaderRouteRouteChildren {
  HeaderBlogSlugRoute: typeof HeaderBlogSlugRoute
  HeaderBlogIndexRoute: typeof HeaderBlogIndexRoute
  HeaderExploreIndexRoute: typeof HeaderExploreIndexRoute
  HeaderPricingIndexRoute: typeof HeaderPricingIndexRoute
  HeaderPrivacyIndexRoute: typeof HeaderPrivacyIndexRoute
  HeaderTermsIndexRoute: typeof HeaderTermsIndexRoute
}

const HeaderRouteRouteChildren: HeaderRouteRouteChildren = {
  HeaderBlogSlugRoute: HeaderBlogSlugRoute,
  HeaderBlogIndexRoute: HeaderBlogIndexRoute,
  HeaderExploreIndexRoute: HeaderExploreIndexRoute,
  HeaderPricingIndexRoute: HeaderPricingIndexRoute,
  HeaderPrivacyIndexRoute: HeaderPrivacyIndexRoute,
  HeaderTermsIndexRoute: HeaderTermsIndexRoute,
}

const HeaderRouteRouteWithChildren = HeaderRouteRoute._addFileChildren(
  HeaderRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  HeaderRouteRoute: HeaderRouteRouteWithChildren,
  DemoRoute: DemoRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  LogInIndexRoute: LogInIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
