/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HandleRouteImport } from './routes/$handle'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as NewRouteImport } from './routes/new'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DemoIndexRouteImport } from './routes/demo/index'
import { Route as ExploreIndexRouteImport } from './routes/explore/index'
import { Route as LogInIndexRouteImport } from './routes/log-in/index'
import { Route as UpdateIndexRouteImport } from './routes/update/index'
import { Route as ApiPagesHandleRouteImport } from './routes/api/pages/$handle'
import { Route as ApiPagesHandleImageUploadRouteImport } from './routes/api/pages/$handle/image-upload'
import { Route as ApiPagesHandleImageUploadCompleteRouteImport } from './routes/api/pages/$handle/image-upload/complete'
import { Route as ApiPagesHandleItemsUploadRouteImport } from './routes/api/pages/$handle/items/upload'
import { Route as ApiPagesHandleItemsUploadCompleteRouteImport } from './routes/api/pages/$handle/items/upload/complete'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HandleRoute = HandleRouteImport.update({
  id: '/$handle',
  path: '/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/demo/',
  path: '/demo/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogInIndexRoute = LogInIndexRouteImport.update({
  id: '/log-in/',
  path: '/log-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdateIndexRoute = UpdateIndexRouteImport.update({
  id: '/update/',
  path: '/update/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPagesHandleRoute = ApiPagesHandleRouteImport.update({
  id: '/api/pages/$handle',
  path: '/api/pages/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPagesHandleImageUploadRoute =
  ApiPagesHandleImageUploadRouteImport.update({
    id: '/image-upload',
    path: '/image-upload',
    getParentRoute: () => ApiPagesHandleRoute,
  } as any)
const ApiPagesHandleImageUploadCompleteRoute =
  ApiPagesHandleImageUploadCompleteRouteImport.update({
    id: '/complete',
    path: '/complete',
    getParentRoute: () => ApiPagesHandleImageUploadRoute,
  } as any)
const ApiPagesHandleItemsUploadRoute =
  ApiPagesHandleItemsUploadRouteImport.update({
    id: '/items/upload',
    path: '/items/upload',
    getParentRoute: () => ApiPagesHandleRoute,
  } as any)
const ApiPagesHandleItemsUploadCompleteRoute =
  ApiPagesHandleItemsUploadCompleteRouteImport.update({
    id: '/complete',
    path: '/complete',
    getParentRoute: () => ApiPagesHandleItemsUploadRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$handle': typeof HandleRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/new': typeof NewRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/demo/': typeof DemoIndexRoute
  '/explore/': typeof ExploreIndexRoute
  '/log-in/': typeof LogInIndexRoute
  '/update/': typeof UpdateIndexRoute
  '/api/pages/$handle': typeof ApiPagesHandleRouteWithChildren
  '/api/pages/$handle/image-upload': typeof ApiPagesHandleImageUploadRouteWithChildren
  '/api/pages/$handle/image-upload/complete': typeof ApiPagesHandleImageUploadCompleteRoute
  '/api/pages/$handle/items/upload': typeof ApiPagesHandleItemsUploadRouteWithChildren
  '/api/pages/$handle/items/upload/complete': typeof ApiPagesHandleItemsUploadCompleteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$handle': typeof HandleRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/new': typeof NewRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/demo': typeof DemoIndexRoute
  '/explore': typeof ExploreIndexRoute
  '/log-in': typeof LogInIndexRoute
  '/update': typeof UpdateIndexRoute
  '/api/pages/$handle': typeof ApiPagesHandleRouteWithChildren
  '/api/pages/$handle/image-upload': typeof ApiPagesHandleImageUploadRouteWithChildren
  '/api/pages/$handle/image-upload/complete': typeof ApiPagesHandleImageUploadCompleteRoute
  '/api/pages/$handle/items/upload': typeof ApiPagesHandleItemsUploadRouteWithChildren
  '/api/pages/$handle/items/upload/complete': typeof ApiPagesHandleItemsUploadCompleteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$handle': typeof HandleRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/new': typeof NewRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/demo/': typeof DemoIndexRoute
  '/explore/': typeof ExploreIndexRoute
  '/log-in/': typeof LogInIndexRoute
  '/update/': typeof UpdateIndexRoute
  '/api/pages/$handle': typeof ApiPagesHandleRouteWithChildren
  '/api/pages/$handle/image-upload': typeof ApiPagesHandleImageUploadRouteWithChildren
  '/api/pages/$handle/image-upload/complete': typeof ApiPagesHandleImageUploadCompleteRoute
  '/api/pages/$handle/items/upload': typeof ApiPagesHandleItemsUploadRouteWithChildren
  '/api/pages/$handle/items/upload/complete': typeof ApiPagesHandleItemsUploadCompleteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$handle'
    | '/llms.txt'
    | '/new'
    | '/sitemap.xml'
    | '/demo/'
    | '/explore/'
    | '/log-in/'
    | '/update/'
    | '/api/pages/$handle'
    | '/api/pages/$handle/image-upload'
    | '/api/pages/$handle/image-upload/complete'
    | '/api/pages/$handle/items/upload'
    | '/api/pages/$handle/items/upload/complete'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$handle'
    | '/llms.txt'
    | '/new'
    | '/sitemap.xml'
    | '/demo'
    | '/explore'
    | '/log-in'
    | '/update'
    | '/api/pages/$handle'
    | '/api/pages/$handle/image-upload'
    | '/api/pages/$handle/image-upload/complete'
    | '/api/pages/$handle/items/upload'
    | '/api/pages/$handle/items/upload/complete'
  id:
    | '__root__'
    | '/'
    | '/$handle'
    | '/llms.txt'
    | '/new'
    | '/sitemap.xml'
    | '/demo/'
    | '/explore/'
    | '/log-in/'
    | '/update/'
    | '/api/pages/$handle'
    | '/api/pages/$handle/image-upload'
    | '/api/pages/$handle/image-upload/complete'
    | '/api/pages/$handle/items/upload'
    | '/api/pages/$handle/items/upload/complete'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HandleRoute: typeof HandleRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  NewRoute: typeof NewRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DemoIndexRoute: typeof DemoIndexRoute
  ExploreIndexRoute: typeof ExploreIndexRoute
  LogInIndexRoute: typeof LogInIndexRoute
  UpdateIndexRoute: typeof UpdateIndexRoute
  ApiPagesHandleRoute: typeof ApiPagesHandleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$handle': {
      id: '/$handle'
      path: '/$handle'
      fullPath: '/$handle'
      preLoaderRoute: typeof HandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/demo'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/': {
      id: '/explore/'
      path: '/explore'
      fullPath: '/explore/'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log-in/': {
      id: '/log-in/'
      path: '/log-in'
      fullPath: '/log-in/'
      preLoaderRoute: typeof LogInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/update/': {
      id: '/update/'
      path: '/update'
      fullPath: '/update/'
      preLoaderRoute: typeof UpdateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pages/$handle': {
      id: '/api/pages/$handle'
      path: '/api/pages/$handle'
      fullPath: '/api/pages/$handle'
      preLoaderRoute: typeof ApiPagesHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pages/$handle/image-upload': {
      id: '/api/pages/$handle/image-upload'
      path: '/image-upload'
      fullPath: '/api/pages/$handle/image-upload'
      preLoaderRoute: typeof ApiPagesHandleImageUploadRouteImport
      parentRoute: typeof ApiPagesHandleRoute
    }
    '/api/pages/$handle/image-upload/complete': {
      id: '/api/pages/$handle/image-upload/complete'
      path: '/complete'
      fullPath: '/api/pages/$handle/image-upload/complete'
      preLoaderRoute: typeof ApiPagesHandleImageUploadCompleteRouteImport
      parentRoute: typeof ApiPagesHandleImageUploadRoute
    }
    '/api/pages/$handle/items/upload': {
      id: '/api/pages/$handle/items/upload'
      path: '/items/upload'
      fullPath: '/api/pages/$handle/items/upload'
      preLoaderRoute: typeof ApiPagesHandleItemsUploadRouteImport
      parentRoute: typeof ApiPagesHandleRoute
    }
    '/api/pages/$handle/items/upload/complete': {
      id: '/api/pages/$handle/items/upload/complete'
      path: '/complete'
      fullPath: '/api/pages/$handle/items/upload/complete'
      preLoaderRoute: typeof ApiPagesHandleItemsUploadCompleteRouteImport
      parentRoute: typeof ApiPagesHandleItemsUploadRoute
    }
  }
}

interface ApiPagesHandleImageUploadRouteChildren {
  ApiPagesHandleImageUploadCompleteRoute: typeof ApiPagesHandleImageUploadCompleteRoute
}

const ApiPagesHandleImageUploadRouteChildren: ApiPagesHandleImageUploadRouteChildren =
  {
    ApiPagesHandleImageUploadCompleteRoute:
      ApiPagesHandleImageUploadCompleteRoute,
  }

const ApiPagesHandleImageUploadRouteWithChildren =
  ApiPagesHandleImageUploadRoute._addFileChildren(
    ApiPagesHandleImageUploadRouteChildren,
  )

interface ApiPagesHandleItemsUploadRouteChildren {
  ApiPagesHandleItemsUploadCompleteRoute: typeof ApiPagesHandleItemsUploadCompleteRoute
}

const ApiPagesHandleItemsUploadRouteChildren: ApiPagesHandleItemsUploadRouteChildren =
  {
    ApiPagesHandleItemsUploadCompleteRoute:
      ApiPagesHandleItemsUploadCompleteRoute,
  }

const ApiPagesHandleItemsUploadRouteWithChildren =
  ApiPagesHandleItemsUploadRoute._addFileChildren(
    ApiPagesHandleItemsUploadRouteChildren,
  )

interface ApiPagesHandleRouteChildren {
  ApiPagesHandleImageUploadRoute: typeof ApiPagesHandleImageUploadRouteWithChildren
  ApiPagesHandleItemsUploadRoute: typeof ApiPagesHandleItemsUploadRouteWithChildren
}

const ApiPagesHandleRouteChildren: ApiPagesHandleRouteChildren = {
  ApiPagesHandleImageUploadRoute: ApiPagesHandleImageUploadRouteWithChildren,
  ApiPagesHandleItemsUploadRoute: ApiPagesHandleItemsUploadRouteWithChildren,
}

const ApiPagesHandleRouteWithChildren = ApiPagesHandleRoute._addFileChildren(
  ApiPagesHandleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HandleRoute: HandleRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  NewRoute: NewRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DemoIndexRoute: DemoIndexRoute,
  ExploreIndexRoute: ExploreIndexRoute,
  LogInIndexRoute: LogInIndexRoute,
  UpdateIndexRoute: UpdateIndexRoute,
  ApiPagesHandleRoute: ApiPagesHandleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
