/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HandleRouteImport } from './routes/$handle'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as entryLayoutRouteRouteImport } from './routes/(entry)/_layout/route'
import { Route as ApiFaviconRouteImport } from './routes/api/favicon'
import { Route as ApiProfileImageRouteImport } from './routes/api/profile-image'
import { Route as ExploreIndexRouteImport } from './routes/explore/index'
import { Route as PricingIndexRouteImport } from './routes/pricing/index'
import { Route as UpdateIndexRouteImport } from './routes/update/index'
import { Route as entryLayoutNewRouteImport } from './routes/(entry)/_layout/new'
import { Route as ApiPagesHandleRouteImport } from './routes/api/pages/$handle'
import { Route as entryLayoutLogInIndexRouteImport } from './routes/(entry)/_layout/log-in/index'
import { Route as ApiPagesHandleImageUploadRouteImport } from './routes/api/pages/$handle/image-upload'
import { Route as ApiPagesHandleImageUploadCompleteRouteImport } from './routes/api/pages/$handle/image-upload/complete'
import { Route as ApiPagesHandleItemsUploadRouteImport } from './routes/api/pages/$handle/items/upload'
import { Route as ApiPagesHandleItemsUploadCompleteRouteImport } from './routes/api/pages/$handle/items/upload/complete'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HandleRoute = HandleRouteImport.update({
  id: '/$handle',
  path: '/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const entryLayoutRouteRoute = entryLayoutRouteRouteImport.update({
  id: '/(entry)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFaviconRoute = ApiFaviconRouteImport.update({
  id: '/api/favicon',
  path: '/api/favicon',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileImageRoute = ApiProfileImageRouteImport.update({
  id: '/api/profile-image',
  path: '/api/profile-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingIndexRoute = PricingIndexRouteImport.update({
  id: '/pricing/',
  path: '/pricing/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdateIndexRoute = UpdateIndexRouteImport.update({
  id: '/update/',
  path: '/update/',
  getParentRoute: () => rootRouteImport,
} as any)
const entryLayoutNewRoute = entryLayoutNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => entryLayoutRouteRoute,
} as any)
const ApiPagesHandleRoute = ApiPagesHandleRouteImport.update({
  id: '/api/pages/$handle',
  path: '/api/pages/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const entryLayoutLogInIndexRoute = entryLayoutLogInIndexRouteImport.update({
  id: '/log-in/',
  path: '/log-in/',
  getParentRoute: () => entryLayoutRouteRoute,
} as any)
const ApiPagesHandleImageUploadRoute =
  ApiPagesHandleImageUploadRouteImport.update({
    id: '/image-upload',
    path: '/image-upload',
    getParentRoute: () => ApiPagesHandleRoute,
  } as any)
const ApiPagesHandleImageUploadCompleteRoute =
  ApiPagesHandleImageUploadCompleteRouteImport.update({
    id: '/complete',
    path: '/complete',
    getParentRoute: () => ApiPagesHandleImageUploadRoute,
  } as any)
const ApiPagesHandleItemsUploadRoute =
  ApiPagesHandleItemsUploadRouteImport.update({
    id: '/items/upload',
    path: '/items/upload',
    getParentRoute: () => ApiPagesHandleRoute,
  } as any)
const ApiPagesHandleItemsUploadCompleteRoute =
  ApiPagesHandleItemsUploadCompleteRouteImport.update({
    id: '/complete',
    path: '/complete',
    getParentRoute: () => ApiPagesHandleItemsUploadRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$handle': typeof HandleRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/favicon': typeof ApiFaviconRoute
  '/api/profile-image': typeof ApiProfileImageRoute
  '/explore/': typeof ExploreIndexRoute
  '/pricing/': typeof PricingIndexRoute
  '/update/': typeof UpdateIndexRoute
  '/new': typeof entryLayoutNewRoute
  '/api/pages/$handle': typeof ApiPagesHandleRouteWithChildren
  '/api/pages/$handle/image-upload': typeof ApiPagesHandleImageUploadRouteWithChildren
  '/log-in/': typeof entryLayoutLogInIndexRoute
  '/api/pages/$handle/image-upload/complete': typeof ApiPagesHandleImageUploadCompleteRoute
  '/api/pages/$handle/items/upload': typeof ApiPagesHandleItemsUploadRouteWithChildren
  '/api/pages/$handle/items/upload/complete': typeof ApiPagesHandleItemsUploadCompleteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$handle': typeof HandleRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/favicon': typeof ApiFaviconRoute
  '/api/profile-image': typeof ApiProfileImageRoute
  '/explore': typeof ExploreIndexRoute
  '/pricing': typeof PricingIndexRoute
  '/update': typeof UpdateIndexRoute
  '/new': typeof entryLayoutNewRoute
  '/api/pages/$handle': typeof ApiPagesHandleRouteWithChildren
  '/api/pages/$handle/image-upload': typeof ApiPagesHandleImageUploadRouteWithChildren
  '/log-in': typeof entryLayoutLogInIndexRoute
  '/api/pages/$handle/image-upload/complete': typeof ApiPagesHandleImageUploadCompleteRoute
  '/api/pages/$handle/items/upload': typeof ApiPagesHandleItemsUploadRouteWithChildren
  '/api/pages/$handle/items/upload/complete': typeof ApiPagesHandleItemsUploadCompleteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$handle': typeof HandleRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/(entry)/_layout': typeof entryLayoutRouteRouteWithChildren
  '/api/favicon': typeof ApiFaviconRoute
  '/api/profile-image': typeof ApiProfileImageRoute
  '/explore/': typeof ExploreIndexRoute
  '/pricing/': typeof PricingIndexRoute
  '/update/': typeof UpdateIndexRoute
  '/(entry)/_layout/new': typeof entryLayoutNewRoute
  '/api/pages/$handle': typeof ApiPagesHandleRouteWithChildren
  '/api/pages/$handle/image-upload': typeof ApiPagesHandleImageUploadRouteWithChildren
  '/(entry)/_layout/log-in/': typeof entryLayoutLogInIndexRoute
  '/api/pages/$handle/image-upload/complete': typeof ApiPagesHandleImageUploadCompleteRoute
  '/api/pages/$handle/items/upload': typeof ApiPagesHandleItemsUploadRouteWithChildren
  '/api/pages/$handle/items/upload/complete': typeof ApiPagesHandleItemsUploadCompleteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$handle'
    | '/llms.txt'
    | '/sitemap.xml'
    | '/api/favicon'
    | '/api/profile-image'
    | '/explore/'
    | '/pricing/'
    | '/update/'
    | '/new'
    | '/api/pages/$handle'
    | '/api/pages/$handle/image-upload'
    | '/log-in/'
    | '/api/pages/$handle/image-upload/complete'
    | '/api/pages/$handle/items/upload'
    | '/api/pages/$handle/items/upload/complete'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$handle'
    | '/llms.txt'
    | '/sitemap.xml'
    | '/api/favicon'
    | '/api/profile-image'
    | '/explore'
    | '/pricing'
    | '/update'
    | '/new'
    | '/api/pages/$handle'
    | '/api/pages/$handle/image-upload'
    | '/log-in'
    | '/api/pages/$handle/image-upload/complete'
    | '/api/pages/$handle/items/upload'
    | '/api/pages/$handle/items/upload/complete'
  id:
    | '__root__'
    | '/'
    | '/$handle'
    | '/llms.txt'
    | '/sitemap.xml'
    | '/(entry)/_layout'
    | '/api/favicon'
    | '/api/profile-image'
    | '/explore/'
    | '/pricing/'
    | '/update/'
    | '/(entry)/_layout/new'
    | '/api/pages/$handle'
    | '/api/pages/$handle/image-upload'
    | '/(entry)/_layout/log-in/'
    | '/api/pages/$handle/image-upload/complete'
    | '/api/pages/$handle/items/upload'
    | '/api/pages/$handle/items/upload/complete'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HandleRoute: typeof HandleRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  entryLayoutRouteRoute: typeof entryLayoutRouteRouteWithChildren
  ApiFaviconRoute: typeof ApiFaviconRoute
  ApiProfileImageRoute: typeof ApiProfileImageRoute
  ExploreIndexRoute: typeof ExploreIndexRoute
  PricingIndexRoute: typeof PricingIndexRoute
  UpdateIndexRoute: typeof UpdateIndexRoute
  ApiPagesHandleRoute: typeof ApiPagesHandleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$handle': {
      id: '/$handle'
      path: '/$handle'
      fullPath: '/$handle'
      preLoaderRoute: typeof HandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(entry)/_layout': {
      id: '/(entry)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof entryLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/favicon': {
      id: '/api/favicon'
      path: '/api/favicon'
      fullPath: '/api/favicon'
      preLoaderRoute: typeof ApiFaviconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile-image': {
      id: '/api/profile-image'
      path: '/api/profile-image'
      fullPath: '/api/profile-image'
      preLoaderRoute: typeof ApiProfileImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/': {
      id: '/explore/'
      path: '/explore'
      fullPath: '/explore/'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing/': {
      id: '/pricing/'
      path: '/pricing'
      fullPath: '/pricing/'
      preLoaderRoute: typeof PricingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/update/': {
      id: '/update/'
      path: '/update'
      fullPath: '/update/'
      preLoaderRoute: typeof UpdateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(entry)/_layout/new': {
      id: '/(entry)/_layout/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof entryLayoutNewRouteImport
      parentRoute: typeof entryLayoutRouteRoute
    }
    '/api/pages/$handle': {
      id: '/api/pages/$handle'
      path: '/api/pages/$handle'
      fullPath: '/api/pages/$handle'
      preLoaderRoute: typeof ApiPagesHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(entry)/_layout/log-in/': {
      id: '/(entry)/_layout/log-in/'
      path: '/log-in'
      fullPath: '/log-in/'
      preLoaderRoute: typeof entryLayoutLogInIndexRouteImport
      parentRoute: typeof entryLayoutRouteRoute
    }
    '/api/pages/$handle/image-upload': {
      id: '/api/pages/$handle/image-upload'
      path: '/image-upload'
      fullPath: '/api/pages/$handle/image-upload'
      preLoaderRoute: typeof ApiPagesHandleImageUploadRouteImport
      parentRoute: typeof ApiPagesHandleRoute
    }
    '/api/pages/$handle/image-upload/complete': {
      id: '/api/pages/$handle/image-upload/complete'
      path: '/complete'
      fullPath: '/api/pages/$handle/image-upload/complete'
      preLoaderRoute: typeof ApiPagesHandleImageUploadCompleteRouteImport
      parentRoute: typeof ApiPagesHandleImageUploadRoute
    }
    '/api/pages/$handle/items/upload': {
      id: '/api/pages/$handle/items/upload'
      path: '/items/upload'
      fullPath: '/api/pages/$handle/items/upload'
      preLoaderRoute: typeof ApiPagesHandleItemsUploadRouteImport
      parentRoute: typeof ApiPagesHandleRoute
    }
    '/api/pages/$handle/items/upload/complete': {
      id: '/api/pages/$handle/items/upload/complete'
      path: '/complete'
      fullPath: '/api/pages/$handle/items/upload/complete'
      preLoaderRoute: typeof ApiPagesHandleItemsUploadCompleteRouteImport
      parentRoute: typeof ApiPagesHandleItemsUploadRoute
    }
  }
}

interface entryLayoutRouteRouteChildren {
  entryLayoutNewRoute: typeof entryLayoutNewRoute
  entryLayoutLogInIndexRoute: typeof entryLayoutLogInIndexRoute
}

const entryLayoutRouteRouteChildren: entryLayoutRouteRouteChildren = {
  entryLayoutNewRoute: entryLayoutNewRoute,
  entryLayoutLogInIndexRoute: entryLayoutLogInIndexRoute,
}

const entryLayoutRouteRouteWithChildren =
  entryLayoutRouteRoute._addFileChildren(entryLayoutRouteRouteChildren)

interface ApiPagesHandleImageUploadRouteChildren {
  ApiPagesHandleImageUploadCompleteRoute: typeof ApiPagesHandleImageUploadCompleteRoute
}

const ApiPagesHandleImageUploadRouteChildren: ApiPagesHandleImageUploadRouteChildren =
  {
    ApiPagesHandleImageUploadCompleteRoute:
      ApiPagesHandleImageUploadCompleteRoute,
  }

const ApiPagesHandleImageUploadRouteWithChildren =
  ApiPagesHandleImageUploadRoute._addFileChildren(
    ApiPagesHandleImageUploadRouteChildren,
  )

interface ApiPagesHandleItemsUploadRouteChildren {
  ApiPagesHandleItemsUploadCompleteRoute: typeof ApiPagesHandleItemsUploadCompleteRoute
}

const ApiPagesHandleItemsUploadRouteChildren: ApiPagesHandleItemsUploadRouteChildren =
  {
    ApiPagesHandleItemsUploadCompleteRoute:
      ApiPagesHandleItemsUploadCompleteRoute,
  }

const ApiPagesHandleItemsUploadRouteWithChildren =
  ApiPagesHandleItemsUploadRoute._addFileChildren(
    ApiPagesHandleItemsUploadRouteChildren,
  )

interface ApiPagesHandleRouteChildren {
  ApiPagesHandleImageUploadRoute: typeof ApiPagesHandleImageUploadRouteWithChildren
  ApiPagesHandleItemsUploadRoute: typeof ApiPagesHandleItemsUploadRouteWithChildren
}

const ApiPagesHandleRouteChildren: ApiPagesHandleRouteChildren = {
  ApiPagesHandleImageUploadRoute: ApiPagesHandleImageUploadRouteWithChildren,
  ApiPagesHandleItemsUploadRoute: ApiPagesHandleItemsUploadRouteWithChildren,
}

const ApiPagesHandleRouteWithChildren = ApiPagesHandleRoute._addFileChildren(
  ApiPagesHandleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HandleRoute: HandleRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  entryLayoutRouteRoute: entryLayoutRouteRouteWithChildren,
  ApiFaviconRoute: ApiFaviconRoute,
  ApiProfileImageRoute: ApiProfileImageRoute,
  ExploreIndexRoute: ExploreIndexRoute,
  PricingIndexRoute: PricingIndexRoute,
  UpdateIndexRoute: UpdateIndexRoute,
  ApiPagesHandleRoute: ApiPagesHandleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
